### ISSUE TITLE
New Account Creation (MHW)

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/MyHbarWallet#122]
Enable account creation with zero balance from MyHbarWallet.

**Comment by kenthejr** [comment]
@mehcode check Carbon as of today. It seems they have hbars working now. Let's figure out a flow for card-to-crypto-to-new-account.

**Comment by Cooper-Kunz** [comment]
Is this something MHW still plans to implement?

It'd be quite helpful versus the current "find someone else to share your pub key with" method MHW uses

Otherwise, we should close the issue, given its > 1 year old
