### ISSUE TITLE
1 Password Integration (MHW)

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/MyHbarWallet#125]
1Password Integration with MHW

**Comment by QuestofIranon** [comment]
Duplicate of #113 ?

**Comment by QuestofIranon** [comment]
@donaldthibeau Duplicate of #113?

**Comment by QuestofIranon** [comment]
It might be interesting to create a project board per Epic so smaller issues can be organized that way. I was kind of experimenting with project organization (github's boards are more limiting than jira or gitlab's, both of which I'm more familiar with using)

**Comment by mehcode** [comment]
The idea with epics is we link related issues into a big list of "this is what needs to be done". The board tracks individual progress but the epic can be thought of as a "tracking issue".

**Comment by QuestofIranon** [comment]
Fair enough, I'll go through and link issues to these epics when I get around to it. I still feel like that's the vague role of the project boards in general though if we wanted to clean up the issue list.
