### ISSUE TITLE
Evaluate and remove unit tests that are no longer needed

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/MyHbarWallet#173]
Due to the change of how modals are handled, some unit tests are no longer needed or need editing. Mainly the `rendered as closed` tests.

**Comment by cacampbell** [comment]
In general, when I wrote snapshot tests, I did a quick boolean count of all possible prop values and tried to make a snapshot for each. 

This isn't really helpful for most, and we should focus on snapshots with meaningful data given as props.

**Comment by QuestofIranon** [comment]
The other issue is that we had tests for modals rendering closed, but now they're removed from the dom if they're closed so they don't render and that results in the tests automatically attempting to rewrite the snapshots everytime.

**Comment by cacampbell** [comment]
Also need to adjust mocks / stubs
