### ISSUE TITLE
Error message for "Enter Account ID" / Not found on network is .. weird.

### ISSUE THREAD

**Issue by mehcode** [hashgraph/MyHbarWallet#192]
![image](https://user-images.githubusercontent.com/753919/67914113-6f9a9a00-fb4c-11e9-98fc-7602cbf12261.png)

Error message wording could be better. 

---

1 - Can we confirm this is a valid error message? For instance, 12421 is said not to exist but there are over 100k accounts and account IDs are sequential. I'm fairly sure this was a deleted account but the error can be confusing.

2 - This error message doesn't follow our other error messages (see below)

![image](https://user-images.githubusercontent.com/753919/67914276-e46dd400-fb4c-11e9-934b-e686b9991273.png)

**Comment by cacampbell** [comment]
Change error messages to be Active voice single sentences in i18n strings. 

These two error messages are valid -- they are the mapped error messages from separate Hedera error codes.
