### ISSUE TITLE
Review success modals and at the very least normalize

### ISSUE THREAD

**Issue by mehcode** [hashgraph/MyHbarWallet#198]
*Send*

![image](https://user-images.githubusercontent.com/753919/67971510-24bf6780-fbca-11e9-85ae-f8846f7ec593.png)

*Create Account*

![image](https://user-images.githubusercontent.com/753919/67971562-36a10a80-fbca-11e9-9e7e-094118cd3a4b.png)

*Upload File*

![image](https://user-images.githubusercontent.com/753919/67971608-4ae50780-fbca-11e9-9e94-93a524d9cd32.png)

*Download File*

> Doesn't have one as it just downloads the file.

**Comment by mehcode** [comment]
MyEtherWallet

https://www.myetherwallet.com/img/garlands.85590a8d.png

![image](https://user-images.githubusercontent.com/753919/67972133-4e2cc300-fbcb-11e9-8333-84036b9b9ccd.png)

**Comment by mehcode** [comment]
https://miro.medium.com/max/400/1*1Llov3rK1GPl6adJuvdJNA.png

**Comment by mehcode** [comment]
Thoughts

 * Make this modal work like our keystore modal if there is an ID to copy

![image](https://user-images.githubusercontent.com/753919/67972322-ab287900-fbcb-11e9-8872-7c70676f3232.png)

 * Move the checkmark out of the modal slightly. Not sure about this one but its intriguing to make the checkmark still big and take up less space.

 * Use the garland image to make the modal seem happier. Haha.

**Comment by mehcode** [comment]
One more note. The File Upload "progress" modal should close and open a second modal that is the success modal.

**Comment by cacampbell** [comment]
One standard ModalSuccess component pls

**Comment by QuestofIranon** [comment]
I feel like the check in a circle could be enhanced, it has a lot of white space and inconsistent thickness.
