### ISSUE TITLE
Success Modal Improvement (See details)

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/MyHbarWallet#207]
via @mehcode 

continuation of #198 

- [x] We need to include more details like "Created account X with an initial balance of Y hbar" ( perhaps as subtext under "Success" )
- [x] The garland image is designed to be flush with the modal border. It looks odd hanging there.
- [x] Make the checkmark look like the modal below where its smaller, inverted, and half-out of the modal.
![](https://miro.medium.com/max/400/1*1Llov3rK1GPl6adJuvdJNA.png)
- [x] "Copy" should say "Copy _______ ID"
- [x] "Continue" Should say Close or Dismiss
- [x] copy button should be mandatory now

**Comment by cacampbell** [comment]
I have no idea how you got a success modal to display without a message, since it's a slot from the enclosing scope :unamused: 

![image](https://user-images.githubusercontent.com/4349395/68038898-3109fa00-fc88-11e9-8fce-01697bd83e8a.png)

**Comment by QuestofIranon** [comment]
I missed that, but vue just ignores the slots if they don't exist. Unfortunately it doesn't look like there is a way to make them mandatory either :/

**Comment by cacampbell** [comment]
#216

**Comment by cacampbell** [comment]
https://files.slack.com/files-pri/T03SN24C3-FQ4K46A15/image.png
