### ISSUE TITLE
Download Success Modal Improvements

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/MyHbarWallet#229]
- [x] remove "With ID" -- it should say "Downloading File {{id}}"
- [x] Have two confirmation buttons with the primary/ blocker being "Save File" which then begins the file download (instead of having it begin as the modal appears)
- [x] reword the previous modal's "Download File" button so that it doesn't imply the download will be starting when it is clicked

**Comment by Austin-Shep** [comment]
im not quite sure where we landed on this one.
