### ISSUE TITLE
Use of comparison Operators on Big Number and other types

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/MyHbarWallet#32]
There are multiple instances of Big Number values being compared with the comparison operators `<`, `==`, and `>` which actually coerce the big number to a number type using `valueOf` before performing the comparison.

Most instances ***should*** be fixed when #9 gets merged in. It would be nice to have a lint for it and a manual audit to ensure they don't occur elsewhere. A pull request at https://github.com/typescript-eslint/typescript-eslint/pull/314 exists for typescript-eslint to add the lint (see also https://palantir.github.io/tslint/rules/strict-comparisons/). Finishing up that PR and re-opening it or creating a new one might be a good first step.

**Comment by Sheng-Long** [comment]
Went through our code, looking for big number operator comparisons - couldn't find any.  I agree that this is something probably better done through a linter after doing that.

I did find a BigNumber Constructor for a variable that was already a BigNumber, though: #55

**Comment by QuestofIranon** [comment]
I think most of them had been cleaned up already. I'm planning to redo my pull request for switching to hbar values once the updates to the hbar wrapper get merged. This will result in less usage of big number.

Also, the ones I saw were primarily in the input checks.

**Comment by QuestofIranon** [comment]
It looks like this is no longer an issue.
