### ISSUE TITLE
Add support for legacy mnemonics from the mobile app

### ISSUE THREAD

**Issue by mehcode** [hashgraph/MyHbarWallet#320]
Enough people are trying this. I believe the current apps check both formats. This should not be added the JS SDK but just added here.

**Comment by robert-at-hedera** [comment]
https://github.com/hashgraph/hedera-wallet-ios/blob/master/HGCApp/Crypto/Mnemonic%26Seed/HGCSeed.m

That should include the translation between "entropy" (seed) and the word list (inlined for maximum fun.)
