### ISSUE TITLE
Access by Hardware popup displays [object Object]

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/MyHbarWallet#373]
Attempting to use the site & access account via Ledger & I'm getting the following popup. 

Not sure what it is intended to display.

![Screen Shot 2020-03-02 at 8 14 22 PM](https://user-images.githubusercontent.com/11776938/75739630-a3d0c380-5cc2-11ea-883f-818a766dc87e.png)

**Comment by mehcode** [comment]
Can you confirm your version? Check the footer at the bottom. Latest should be: `v0.5.0+08cf150`.

**Comment by Cooper-Kunz** [comment]
Yes, it seems to be `v0.5.0+08cf150` @mehcode

**Comment by mehcode** [comment]
Additionally please state your browser, browser version, OS, etc.

**Comment by mehcode** [comment]
I just tried on macOS Catalina 10.15.3, Chrome 82 and it worked fine. The specific screen you show is a bug we had a few versions ago. I don't think it's possible we use the `alert` function any more. 

Please give it a go on a private browser tab at least to make sure there isn't some cache somewhere.

**Comment by Cooper-Kunz** [comment]
Thanks for your help @mehcode! Seems to be a much bigger improvement, so i'm sure I had something cached. It's harder to recreate in private, but for instance, if I'm on a different app, e.g. bitcoin, or choose "X" to "exporting public key #0" it still occurs. Far less likely, but be great to get a better error message.

**Comment by Cooper-Kunz** [comment]
Also for some reason when the app cancels, e.g. I push "X" or whenever there's an error, MyHbarWallet seemingly attempts to open my mailing application. I can send a video over Slack or similar, if needed.

**Comment by mehcode** [comment]
@Cooper-Kunz I can recreate that `alert` issue you're getting. I'm honestly quite stumped. It's not supposed to be able to happen as we simply don't call `alert` anywhere in our code. This means that some library that's in use at that time is calling `alert`.

---

> Also for some reason when the app cancels, e.g. I push "X" or whenever there's an error, MyHbarWallet seemingly attempts to open my mailing application. I can send a video over Slack or similar, if needed.

I'd appreciate a video if you can. When an error happens an internal error dialog should pop-up and if you click the submit button there it should open up your mail client. I'm curious how it's occurring for you.

**Comment by mehcode** [comment]
Going to close the issue as the opening issue is not occuring.
