### ISSUE TITLE
Remove red coloring and "not recommended" on /access-my-account

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/MyHbarWallet#406]
Hi team,

Curious if we could consider removing from this page: https://myhbarwallet.com/access-my-account
• "Not recommended” red text
• Red hover state (change to green, like Hardware option?) 
![image (13)](https://user-images.githubusercontent.com/3035858/84205400-e6443200-aa61-11ea-9703-fc2588ad2011.png)

Understand why this is the way it is — but upon deprecation of Hedera mobile wallet, this option will be only way for folks to access their Hedera accounts and it feels a bit scary.

**Comment by mehcode** [comment]
I can agree. This was copied from MyEtherWallet. It is a bit heavy handed. The only thing I would want do is keep the red warning for "Access by Private Key" as that is actually unsafe.

cc @cacampbell

**Comment by cacampbell** [comment]
Sounds good, I will take a swing at cleaning up the warnings / recommendations text shortly :thumbsup:
