### ISSUE TITLE
Enable Ledger Support in Chromium Browser

### ISSUE THREAD

**Issue by cacampbell** [hashgraph/MyHbarWallet#411]
Should work in Chromium too via WebUSB transport.

**Comment by UGatgithub** [comment]
I expect it might be the same enhancement to make it work with latest Edge browser also, which is based on the Chromium engine, or?

**Comment by cacampbell** [comment]
Update to anyone watching -- current versions of MHW use the ledger "is webusb supported?" callback to enable or disable ledger features.
