### ISSUE TITLE
Phishing

### ISSUE THREAD

**Issue by BreakawayGlenn** [hashgraph/MyHbarWallet#412]
Attempted to log in to https://myhbarwallet.com/ and Avast gave me a warning: 
Whew! We've just saved you from an infected website
INfected URL: https://myhbarwallet.com
Threat: URL:Phishing

**Comment by mehcode** [comment]
Avast has dozens of false positives. We've submitted the URL to Avast multiple times. Not much we can do from our end.

https://MyHbarWallet.com is the correct link.

**Comment by BreakawayGlenn** [comment]
Thank you.
