### ISSUE TITLE
Device communication failed

### ISSUE THREAD

**Issue by monttix** [hashgraph/MyHbarWallet#417]
![EtnpPsPWQA06MhW](https://user-images.githubusercontent.com/36518252/107698900-8f0ff480-6cb5-11eb-88f0-e1f0b0ee145b.jpg)

Hello I have problem in connecting the last version of website with my ledger, I have only 1 browser that show me a old version of myhbarwallet and work (maybe old cache) all the other browser and different system not work for me, attached the different version (the old work, the last not work) What I need to do?

![1](https://user-images.githubusercontent.com/36518252/107698917-946d3f00-6cb5-11eb-9653-9ea07e63b1e6.PNG)
![2](https://user-images.githubusercontent.com/36518252/107698921-96cf9900-6cb5-11eb-8c63-4d54ea839027.PNG)

**Comment by maxlibin** [comment]
I have similar problem

<img width="826" alt="Screenshot 2021-02-18 at 9 11 26 PM" src="https://user-images.githubusercontent.com/1277038/108362090-4369c780-722e-11eb-8427-d2d6475625da.png">

**Comment by maxlibin** [comment]
> I have similar problem
> 
> <img alt="Screenshot 2021-02-18 at 9 11 26 PM" width="826" src="https://user-images.githubusercontent.com/1277038/108362090-4369c780-722e-11eb-8427-d2d6475625da.png">

my bad, I should open ledger HBAR first before clicking on continue.
