### ISSUE TITLE
Running locally token operations on previewnet

### ISSUE THREAD

**Issue by failfmi** [hashgraph/MyHbarWallet#418]
Hello,
when trying to run MyHbarWallet locally on `previewnet`, token api calls tend to timeout or end with CORS issues.
![image](https://user-images.githubusercontent.com/20928965/112009953-853ca500-8b2f-11eb-8fe3-1fc691f11b8a.png)
That being said, relationships with tokens are not shown (it says you do not have any token relationships, but the account has).

**Comment by failfmi** [comment]
Update: Same errors occur at `myhbarwallet.com` as well.

**Comment by cacampbell** [comment]
@failfmi Hi! Thanks for submitting this issue. 

Right now, MHW depends on the Kabuto API to fetch token information. The Kabuto API does not support previewnet at this time, unfortunately. 

Not much we can do about it right now, but either a change to the hedera API or adding support for previewnet to Kabuto are probably what will happen in the near future.
