### ISSUE TITLE
Ledger Nano - QR code / public key not displaying in Chrome

### ISSUE THREAD

**Issue by LopsidedJoaw** [hashgraph/MyHbarWallet#419]
I am following the steps to create a new Hedera wallet for use with a Ledger Nano using MyHBARWallet as detailed on the Hedera website (https://help.hedera.com/hc/en-us/articles/360002155878-How-do-I-set-up-the-Ledger-Nano-S-X-for-use-with-HBAR-cryptocurrency-#breadcrumb). 

During step 12 in section 3a ("The QR code of your Ledger Nano is displayed. Leave this screen up, we will be scanning this code a few steps later") no QR code is displayed on MyHBARWallet.com. Furthermore, if you click "copy public key" nothing is copied.

<img width="594" alt="Screenshot 2021-05-01 at 10 13 42" src="https://user-images.githubusercontent.com/37964292/116777900-c5644100-aa66-11eb-9fb3-59cf4f944b1a.png">

I have tried using two different Ledger Nano X devices, both with the latest firmware (1.6.1).

**Comment by cacampbell** [comment]
Hi, yup. 

Will be addressed shortly.

**Comment by cacampbell** [comment]
Fixed in latest deploy to myhbarwallet.com
