### ISSUE TITLE
Token transfer impossible - gives insufficient token balans

### ISSUE THREAD

**Issue by MilesNHH** [hashgraph/MyHbarWallet#421]
Hi there, 
never used github before, so not sure if Im doing it right!

I tried to transfer tokens, but somehow I got the error 'insufficient token balance'. It worked with two tokens, and some others didnt work (at least hbarbarian and basil). It didnt make any sense because there was sufficient balance.

I tried with hex, which gave me the same error 'you don't have enough tokens'. So I thought maybe it was a hedera issue. However, I now succeeded in transferring all tokens with Dode Cane wallet. So, therefore I guess it must be an issue with Myhbarwallet and hex.

Do say if you need more info.

**Comment by cacampbell** [comment]
Hi, 

We are currently working on the HTS functionality of MHW, and you should expect a better experience when version 0.6.0 releases sometime in the next week.

**Comment by cacampbell** [comment]
The issue is likely in looking up token information, fyi

**Comment by MilesNHH** [comment]
Hello Chris! Thank you for your answer :)

**Comment by cacampbell** [comment]
try next.myhbarwallet.com! 

Report any issues you experience here
