### ISSUE TITLE
Cannot log into MHW. 

### ISSUE THREAD

**Issue by zkwrl** [hashgraph/MyHbarWallet#423]
Cannot log into MHW. 

MHW recognizes the Ledger Nano X and connects.
Public keys match.
When I input my account number into MHW, click "Continue," and confirm on the Nano X, MHW just resets the "Continue" button instead of proceeding to my usual account page. 

This happened before and after I refreshed the web page, updated and reloaded Chrome, updated the Hedera app on the Nano X, and updated the firmware on the Nano X.

**Comment by cacampbell** [comment]
Hello, 

If you are on a Mac, restarting your computer and clearing the NVRAM (google) can sometimes fix connection issues for Chrome 91.
