### ISSUE TITLE
Keys page has button with "Copy Private Key" text on Public key KeyInput

### ISSUE THREAD

**Issue by kgurnani** [hashgraph/MyHbarWallet#539]
### Description

After getting into the wallet using ledger and going into de Keys page, it shows a button with the text "Copy Private Key" on the Public key KeyInput component. [It looks like this value is hardcoded (I may be wrong).](https://github.com/hashgraph/MyHbarWallet/blob/main/src/components/base/KeyInput.vue#L30) I think it should show "Copy Public Key".

### Steps to reproduce

1. Access wallet using ledger.
2. Go to Keys page.
3. There is a button with "Copy Private Key" after Public key.

### Additional context

![keys-mhw-private-key-copy-label](https://user-images.githubusercontent.com/48936235/131951447-5a2eafed-0ff3-4579-986f-62351d7eb322.jpg)

### Hedera network

mainnet

### Version

v0.6.5+a200a92e

### Operating system

Windows

**Comment by cacampbell** [comment]
lol, oops. Thank you for the report. Will fix.
