### ISSUE TITLE
Add a release.sh script

### ISSUE THREAD

**Issue by mehcode** [hashgraph/MyHbarWallet#57]
- [ ] Run `yarn version` to bump the version 
 - [ ] Tag the version using Git
 - [ ] Build and publish electron artifacts to GitHub Releases

**Comment by QuestofIranon** [comment]
Doing this as part of #56

**Comment by QuestofIranon** [comment]
Any reason not to use https://www.electron.build/configuration/publish?

**Comment by mehcode** [comment]
Not that I can tell. We just need to publish to GitHub Releases for now.

**Comment by mehcode** [comment]
Reading through that I would *like* to publish on every commit to master. That sounds like we need to setup a digital ocean space?

**Comment by QuestofIranon** [comment]
It looks like it, unless applify has some sort of cd support. I looked into it last night and

**Comment by QuestofIranon** [comment]
Due to the change to applify this is no longer needed.
