### ISSUE TITLE
Staking page fails to load

### ISSUE THREAD

**Issue by matthewmarcus** [hashgraph/MyHbarWallet#592]
### Description

I've attempted to use MHW (online version) on several different browsers (Brave, Safari, Chrome) on several different computers (Mac and Windows). No matter what I try, I'm unable to access the Staking page.

Every time I do, the page briefly loads, shows some elements and then quickly goes blank. When looking at the inspector, there is an error looping over and over very fast. See attached log and screenshot.

I've attempted access to the Staking page using several different Hedera wallets as well without any luck.

### Steps to reproduce

1. Visit https://myhbarwallet.com
2. Access your wallet
3. Click on Staking menu item

### Additional context

![Screenshot 2023-01-29 at 2 38 46 PM](https://user-images.githubusercontent.com/2431431/215354598-688e1b33-1e80-42e1-9eee-f668059dc09c.jpg)

[myhbarwallet.com-1675024661631.log](https://github.com/hashgraph/MyHbarWallet/files/10530799/myhbarwallet.com-1675024661631.log)

### Hedera network

mainnet

### Version

v0.6.6+b50cf55

### Operating system

macOS

**Comment by kenthejr** [comment]
This is an out of bounds error on the Staking page. I'll submit a PR.
