### ISSUE TITLE
Account creation failure

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/MyHbarWallet#6]
Creating an account from the "Create Account" feature in MHW throws an error stating not enough balance even the amount indicated is less than account balance.
<img width="1397" alt="Screen Shot 2019-09-17 at 11 59 38 AM" src="https://user-images.githubusercontent.com/42808726/65058694-b2a90100-d942-11e9-84d9-f19aebe193df.png">

**Comment by mehcode** [comment]
This should be fixed now. Thanks for reporting the issue.
