### ISSUE TITLE
End To End Tests are failing on expected "visible" but got: "not visible"

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/MyHbarWallet#98]

**Comment by cacampbell** [comment]
Please god lets make the e2e tests work again. 

They save our asses so many times.

**Comment by Sheng-Long** [comment]
Seems to work on 4 separate machines right now.  I believe that pause(500) is sometimes needed instead of waitForElement() because elements are sometimes visible but don't have the time to render their values.
